module.exports = {
    
    token: 'MTI0NTE5OTExOTgyMDEyODM1OA.G6wVBb.Lxi8rgDnDbPM03vKwyEM3EqsfCgbkm1cIcbt7c', 
    status: '.gg/test',
    developerGuildID: '', 
    database: '', 

    
    ticketName: 'ticket-',
    ticketDescription: '🌿 Ticket aberto por',
    ticketCreate: '✅ Seu ticket foi criado',
    ticketAlreadyExist: 'Desculpe, mas você já possui um ticket aberto.',
    ticketNoPermissions: 'Desculpe, mas você não tem permissão para fazer isso.',
    ticketError: 'Alguma coisa deu errado, tente novamente mais tarde.',
    ticketMessageTitle: 'Stack.gg - Ticket',
    ticketMessageDescription: '<:br:1237898680015523952> | Em breve, um membro da nossa equipe de moderação cuidará da sua solicitação.\n\n <:en:1237898681668206614> | A member of our moderation team will shortly take care of your request.\n',
    ticketClose: 'Fechar',
    ticketCloseEmoji: '📪',
    ticketLock: 'Bloquear',
    ticketLockEmoji: '🔒',
    ticketUnlock: 'Desbloquear',
    ticketUnlockEmoji: '🔓',
    ticketClaim: 'Assumir',
    ticketClaimEmoji: '👋',
    ticketManage: 'Membros',
    ticketManageEmoji: '➕',
    ticketManageMenuTitle: 'Escolha um membro.',
    ticketManageMenuEmoji: '❔',
    ticketCloseTitle: 'O ticket está sendo fechado...',
    ticketCloseDescription: 'O ticket será fechado em 5 segundos.',
    ticketSuccessLocked: 'O ticket foi bloqueado com sucesso.',
    ticketAlreadyLocked: 'O ticket já está bloqueado.',
    ticketSuccessUnlocked: 'O ticket foi desbloqueado com sucesso.',
    ticketAlreadyUnlocked: 'O ticket já está desbloqueado.',
    ticketSuccessClaim: 'O ticket foi assumido por',
    ticketAlreadyClaim: 'O ticket já foi assumido por',
    ticketDescriptionClaim: ', foi assumido por',
    ticketTranscriptMember: 'Membro:',
    ticketTranscriptTicket: 'Ticket:',
    ticketTranscriptClaimed: 'Assumido:',
    ticketTranscriptModerator: 'Moderador:',
    ticketTranscriptTime: 'Hora:',
    ticketMemberAdd: 'foi adicionado ao ticket.',
    ticketMemberRemove: 'foi removido do ticket.',
}